### PR TITLE
validate region

### PR DESCRIPTION
**Pull request by nph4rd**
## Summary by CodeRabbit

- **New Features**
  - Added validation for AWS EC2 regions to ensure only valid regions can be used when creating instances.

- **Updates**
  - Updated the EC2 image reference to "agentd-ubuntu-22.04-20240529073401" for improved compatibility.
  - Version bump from "0.2.85" to "0.2.86" for the `agentdesk` project.

### CODE REVIEW

**Comment by pbarker** [comment]
okay awesome, we do still need to fix:

We should add a check that the given region is in one of the supported regions.

This also makes https://github.com/agentsea/agentdesk/blob/main/agentdesk/vm/img.py#L20 this ami ID invalid. We will need to update https://github.com/agentsea/agentdesk/blob/main/agentdesk/vm/ec2.py#L69 to fetch the ami ID by image name, something like:

```py
import boto3

def find_ami_by_name(ami_name, region):
    ec2_client = boto3.client('ec2', region_name=region)
    
    response = ec2_client.describe_images(
        Filters=[
            {
                'Name': 'name',
                'Values': [ami_name]
            }
        ]
    )
    
    images = response.get('Images', [])
    
    if not images:
        print(f"No AMI found with the name: {ami_name}")
        return None
    
    # Assuming the first image in the response is the desired one
    ami = images[0]
    return ami
    
```
The ami name is agentd-ubuntu-22.04-20240529073401

**Comment by nph4rd** [comment]
@pbarker - yeah but it looks like the ID is still the same! 🤷

**Comment by nph4rd** [comment]
@pbarker - this should work. I was able to create an instance in `us-west-2` with this code. The AMI ID was good.

**Comment by pbarker** [comment]
looks good thanks!

**Review by pbarker — APPROVED** [review]

**Pull request merged**
